### ISSUE TITLE
NAs introduced by coercion

### ISSUE THREAD

**Issue by katsikora** [gtrichard/deepStats#15]
Hi Gautier,

I'm running this computeMatrix command:
########################################################################
computeMatrix scale-regions -R /data/boehm/sikora/iwanami/A637/workspaceR.WG.mq10.PCRrm.se4.LG/A637.hypo.bed /data/boehm/sikora/iwanami/A637/workspaceR.WG.mq10.PCRrm.se4.LG/A637.hyper.bed /data/boehm/sikora/iwanami/A637/workspaceR.WG.mq10.PCRrm.se4.LG/A637.unchanged.bed \
-S $BWdir/H3K9me3.merged.filtered.log2ratio.over_LaueIN.merged.bw $BWdir/H3K4me1.merged.filtered.log2ratio.over_Murphy.IN.merged.bw $BWdir/H3K4me3.merged.filtered.log2ratio.over_Murphy.IN.merged.bw $BWdir/H3K27ac.merged.filtered.log2ratio.over_Murphy.IN.merged.bw $BWdir/H3K27me3.merged.filtered.log2ratio.over_Murphy.IN.merged.bw $BWdir/H2AFV.merged.filtered.log2ratio.over_Murphy.IN.merged.bw $BWdir/H3K14ac.merged.filtered.log2ratio.over_Murphy.IN.merged.bw \
-a 100 -b 100 --regionBodyLength 500 -o $OUTDIR/deepTools/matrix_A637all_Laue.Murphy.merged.scaled500.gz \
--outFileNameMatrix deeptools_computeMatrix_output.txt --missingDataAsZero \
-p 6
##################################################################
then this deepStats command:
##########################################################################
dsCompareCurves -i $OUTDIR/deepTools/matrix_A637all_Laue.Murphy.merged.scaled500.txt -o $OUTDIR/deepStats \
--signalName "ChIP-seq normalized Log2ratio" \
--scoreLabel "H3K9me3;H3K4me1;H3K4me3;H3K27ac;H3K27me3;H2AFV;H3K14ac" \
--regionLabel "HypoDMRs;HyperDMRs;UnchangedDMRs" \
--comparison regions -b 1000 -p 20 \
--firstRegionName Start --secondRegionName End
#######################################################################
and I'm getting this error:
#####################################################################
2020-04-29 14:39:02 Extracting metadata from file:
    /data/processing/sikora/TB/20200429transgenerational_manuscript_requests_deepStats/deepTools/matrix_A637all_Laue.Murphy.merged.scaled500.txt ... Done!
Warning messages:
1: NAs introduced by coercion 
2: NAs introduced by coercion 
2020-04-29 14:39:02 --comparison is set: comparing regions.
2020-04-29 14:39:02 Boostraps starting with 20 cores, for each group:
   Number of bootstraps to perform = 1000 
   Number of bins to analyze = 70.85714 
2020-04-29 14:39:02 Starting to boostrap values for the following group:
   Genomic score used: H3K9me3 
Error in line_index_start[group]:line_index_end[group] : NA/NaN argument
Calls: [ -> [.tbl_df
Execution halted
#########################################################################
I used deepTools 3.3. and deepStats 0.4 from conda.

Can you help?

Thanks and best wishes,
Katarzyna

**Comment by gtrichard** [comment]
Hello @katsikora  I hope you are fine.

Is it possible to send me the data ? I guess there are NAs or perhaps special characters for some regions, or something that creates NAs, and the boostrap is breaking because of those NAs. 

Having a look at the data would help a lot to fix this bug. I think a simple na.omit() would fix the problem, but it might be too extreme, and perhaps NAs can be converted to 0 (I think it depends how the bedGraphs are generated, some can have NAs and are thus reported as such instead of 0 by deepTools computeMatrix),

All the best.
Gautier

**Comment by katsikora** [comment]
Hi Gautier,

thanks, all fine here. How are you doing?

I can send you the data. Can you ping me from your new email address on my institute email address? 

Best,

Katarzyna

**Comment by gtrichard** [comment]
Thank you for the data.

I think the bug is happening because the head lines are failing to be read by dsCompareCurves.  Usually the head lines should resemble the following :
```
#genes:56500
#downstream:1000    upstream:1000    body:1000    bin size:50    unscaled 5 prime:0    unscaled 3 prime:0
signal1 signal signal1 signal1 ...... signal2 signal2 signal2 signal2 .....
0.3114 0.0547 0.5545 0.678 0.6687 0.66874 ...
0.7842 1.2451 0.8799 ...
```

In your data, I find the following:

```
@{"upstream":[100,100,100,100,100,100,100],"downstream":[100,100,100,100,100,100,100],"body":[500,500,500,500,500,500,500],"bin size":[10,10,10,10,10,10,10],"ref point":[null,null,null,null,null,null,null],"verbose":false,"bin avg type":"mean","missing data as zero":true,"min threshold":null,"max threshold":null,"scale":1,"skip zeros":false,"nan after end":false,"proc number":6,"sort regions":"keep","sort using":"mean","unscaled 5 prime":[0,0,0,0,0,0,0],"unscaled 3 prime":[0,0,0,0,0,0,0],"group_labels":["file1.bed","file2.bed",file3.bed"],"group_boundaries":[0,164,243,3664],"sample_labels":["signal1","signal2",...],"sample_boundaries":[0,70,140,210,280,350,420,490]}
chr1	1	1000	chr1:1-1000	.	.	-0.025983	-0.025983	-0.208279	-0.329810 ...
```

By reading the documentation of deepTools computeMatrix, I don't understand what triggers the first format output versus your format output... I would thus need to re-encode the metadata parser depending on if the file starts with @ or # ... But if I can recommend a way to process the computeMatrix file in order to avoid your format, I guess it would be preferable.

**Comment by katsikora** [comment]
Hi Gautier,

thanks a lot for looking into it!

Is deepStats compatible with a particular deepTools version? I used 3.3.
Some differences in my code to the example on your github page are region scaling instead of reference point (this I want to have), and I've added -- missingDataAsZero as I thought this was responsible for the deepStats issue.

Let me know if you have any recommendations.

Best,

Katarzyna

**Comment by gtrichard** [comment]
I tested computeMatrix on a recent version of deeptools, this is what `conda list` gives me:

```
# packages in environment at /home/genouest/inra_umr1349/grichard/miniconda3/envs/deeptools:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
blas                      1.0                    openblas
bzip2                     1.0.8                h7b6447c_0
ca-certificates           2020.1.1                      0
certifi                   2019.11.28               py37_0
curl                      7.67.0               hbc83047_0
cycler                    0.10.0                   py37_0
deeptools                 3.3.2                      py_1    bioconda
deeptoolsintervals        0.1.9            py37h516909a_0    bioconda
freetype                  2.9.1                h8a8886c_1
icu                       58.2                 h9c2bf20_1
intel-openmp              2019.4                      243
kiwisolver                1.1.0            py37he6710b0_0
krb5                      1.16.4               h173b8e3_0
ld_impl_linux-64          2.33.1               h53a641e_7
libcurl                   7.67.0               h20c2e04_0
libdeflate                1.0                  h14c3975_1    bioconda
libedit                   3.1.20181209         hc058e9b_0
libffi                    3.2.1                hd88cf55_4
libgcc-ng                 9.1.0                hdf63c60_0
libgfortran-ng            7.3.0                hdf63c60_0
libopenblas               0.3.6                h5a2b251_2
libpng                    1.6.37               hbc83047_0
libssh2                   1.8.2                h1ba5d50_0
libstdcxx-ng              9.1.0                hdf63c60_0
matplotlib-base           3.1.2            py37hef1b27d_1
mkl                       2019.4                      243
mkl-service               2.3.0            py37he904b0f_0
ncurses                   6.1                  he6710b0_1
nomkl                     3.0                           0
numpy                     1.18.1           py37h94c655d_0
numpy-base                1.18.1           py37h2f8d375_1
openssl                   1.1.1d               h7b6447c_3
pip                       20.0.2                   py37_1
plotly                    4.4.1                      py_0
py2bit                    0.3.0            py37h14c3975_2    bioconda
pybigwig                  0.3.17           py37hc013797_0    bioconda
pyparsing                 2.4.6                      py_0
pysam                     0.15.3           py37hda2845c_1    bioconda
python                    3.7.6                h0371630_2
python-dateutil           2.8.1                      py_0
readline                  7.0                  h7b6447c_5
retrying                  1.3.3                    py37_2
scipy                     1.3.2            py37he2b7bc3_0
setuptools                45.1.0                   py37_0
six                       1.14.0                   py37_0
sqlite                    3.30.1               h7b6447c_0
tk                        8.6.8                hbc83047_0
tornado                   6.0.3            py37h7b6447c_0
wheel                     0.34.1                   py37_0
xz                        5.2.4                h14c3975_4
zlib                      1.2.11               h7b6447c_3
```

Command line used:
```
computeMatrix scale-regions -S FAIRE_embryos/*log2*bw -R summits_inter_F_A.bed summits_inter_F_X.bed summits_inter_M_A.bed summits_inter_M_X.bed -o test.matrixDT -bs 10 --sortRegions no --beforeRegionStartLength 500 --afterRegionStartLength 500 --regionBodyLength 100 --missingDataAsZero --outFileNameMatrix test.matrixR3
```

And got the expected format when checking `test.matrixR` (output is equal to only 0 because I was using reference points, i.e. 1bp regions so everything got skipped since bs is 10):
```
#summits_inter_F_A.bed:1183     summits_inter_F_X.bed:515       summits_inter_M_A.bed:1496      summits_inter_M_X.bed:461
#downstream:500 upstream:500    body:100        bin size:10     unscaled 5 prime:0      unscaled 3 prime:0
summits_inter_F_A.bed:1183      summits_inter_F_X.bed:515       summits_inter_M_A.bed:1496      summits_inter_M_X.bed:461       T0A_merged_sorted_log2_10_smooth        T0A_merged_sorted_log2_10_smooth  ...
0       0       0       0       0       0 ...

```

**Comment by gtrichard** [comment]
So still, I don't get what triggers the format you got,  `scale-regions` and `--missingDataAsZero` aren't involved...

**Comment by katsikora** [comment]
Hi Gautier,

I was able to find out the source of the issue: the matrix I passed to deepStats and sent to you was generated with <code>-o</code> in deepTools as gzipped matrix, and then unzipped. I have now instead passed a matrix generated with <code>--outFileNameMatrix</code> in deepTools, and this worked with deepStats.

**Comment by gtrichard** [comment]
Hi Katarzyna,

Ok! At some point I thought I fixed the npz support, but I'll have to have a look once again it seems!

Thank you for the input.
