### ISSUE TITLE
requirement 

### ISSUE THREAD

**Issue by LeilyR** [gtrichard/deepStats#6]
could you please add the requirement file for the dependencies.

**Comment by gtrichard** [comment]
Hum why do you need it ? Conda is taking care of it. Otherwise you can follow the guide for the notebooks.

**Comment by LeilyR** [comment]
I was getting some package error. Can tell you details on Monday

**Comment by LeilyR** [comment]
dsCompareCurves -h
Error: package or namespace load failed for ‘tidyverse’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/data/processing3/leily/miniconda3/envs/deepstats/lib/R/library/haven/libs/haven.so':
  /data/processing3/leily/miniconda3/envs/deepstats/lib/R/library/haven/libs/haven.so: undefined symbol: libiconv
Execution halted

**Comment by gtrichard** [comment]
```
conda create -c bioconda -c conda-forge -n deepStats python=3.7 deepStats
conda activate deepStats
dsCompareCurves -h
```

It did the trick.
