### ISSUE TITLE
Error: package or namespace load failed for ‘tidyverse’

### ISSUE THREAD

**Issue by LeilyR** [gtrichard/deepStats#7]
I cannot run the code, it fails with this error:
Error: package or namespace load failed for ‘tidyverse’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/the/path/to/my/miniconda3/envs/deepstats/lib/R/library/haven/libs/haven.so':
  the/path/to/my/miniconda3/envs/deepstats/lib/R/library/haven/libs/haven.so: undefined symbol: libiconv
Execution halted

**Comment by gtrichard** [comment]
How did you install it ?

**Comment by LeilyR** [comment]
via conda

**Comment by gtrichard** [comment]
Related to https://github.com/gtrichard/deepStats/issues/6

**Comment by LeilyR** [comment]
previously i was 
`conda create -c bioconda -c conda-forge -n deepStats python=3.7`
`conda activate deepStats `
`conda install deepstats`
and I was producing that error , doing it as it is said in documentation
`conda create -c bioconda -c conda-forge -n deepStats python=3.7 deepStats`
`conda activate deepStats`
solved the issue.
